# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

ANDROID_KEY_ALIAS = ENV["ANDROID_KEY_ALIAS"]
ANDROID_KEY_PASSWORD = ENV["ANDROID_KEY_PASSWORD"]
ANDROID_STORE_PASSWORD = ENV["ANDROID_STORE_PASSWORD"]

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

   desc "clean"
   lane :clean do
     gradle(task: "clean")
   end

    desc "Build dev"
    lane :build_dev do
      gradle(
         task: "assemble",
         build_type: "debug", #this is supposed to make debug build
       )

    end

    desc "Build release"
    lane :build_apk do
     gradle(
        task: "assemble",
        build_type: "Release",
        properties: {
            "android.injected.signing.store.file" => "/home/runner/work/ktorDemo/ktorDemo/jks/ktorcrud.jks",
            "android.injected.signing.store.password" => ANDROID_STORE_PASSWORD,
            "android.injected.signing.key.alias" => ANDROID_KEY_ALIAS,
            "android.injected.signing.key.password" => ANDROID_KEY_PASSWORD,
          }
      )
    end
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
end
