name: Android Build


on:
  push:
    branches:
      - 'master'


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: Install Bundler
        run: bundle install
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build apk
        run: bundle exec fastlane build_apk
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/release/app-release.apk
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path:
            ${{ github.workspace }}/app/build/outputs/apk/release