name: Android Release


on:
  push:
    branches:
      - 'master'


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ANDROID_KEY_ALIAS: ${{secrets.ANDROID_KEY_ALIAS}}
      ANDROID_KEY_PASSWORD: ${{secrets.ANDROID_KEY_PASSWORD}}
      ANDROID_STORE_PASSWORD: ${{secrets.ANDROID_STORE_PASSWORD}}
      ANDROID_SIGNING_KEY: ${{secrets.ANDROID_SIGNING_KEY}}
      ANDROID_KEYSTORE: ${{secrets.RELEASE_KEYSTORE}}
      RUNNER_PATH: /home/runner/work/ktorDemo/ktorDemo
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: Install Bundler
        run: bundle install
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Keystore
        run: |
          echo "ANDROID_KEYSTORE" > ktorcrud.jks.b64
          base64 -d -i keystore.jks.b64 > app/jks/ktorcrud.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
      - name: Build apk
        run: bundle exec fastlane build_apk
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path:
            ${{ github.workspace }}/app/build/outputs/apk/release