name: Android Build


on:
  push:
    branches:
      - 'master'


jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install
      - name: Build app
        run: bundle exec fastlane build_dev