name: Android Build


on:
  push:
    branches:
      - 'master'


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Set up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0 # omit if .ruby-version file exists in project, or replace with your team’s supported ruby version
      - name: Install Bundler
        run: bundle install
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Install gems
#        run: bundle update
#      -run: bundle install
#      - name: supply init
#        run: bundle exec fastlane supply init
#      - name: Build app
#        run: bundle exec fastlane build_dev
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Build bundle
        run: bundle exec fastlane build_bundle
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-debug.apk
#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: assets
#          path:
#            ${{ github.workspace }}/app/build/outputs/bundle/release