name: Android Build


on:
  push:
    branches:
      - 'master'


jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/checkout@v2
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0 # omit if .ruby-version file exists in project, or replace with your team’s supported ruby version
          bundler-cache: true
      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install
      - name: Build app
        run: bundle exec fastlane android test